export const REDUX_LS_KEY = 'REDUX_LS_KEY'
export const REDUX_LS_KEY_COUNT = 'REDUX_LS_KEY_COUNT'
export const PRODUCT_DETEIL = 'ProductDetail'
export const REVIEWS_LS_KEY = 'REVIEWS_LS_KEY'
export const USERS_LS_KEY = 'USERS_LS_KEY'
export const REVIEWS = 'REVIEWS'
